<a href="https://colab.research.google.com/github/Vaishnav2804/Reinforcement-Learning-Notebooks/blob/main/Bellman_Equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Bellman Equation:
 is a fundamental concept in Reinforcement Learning and is closely related to the Markov Decision Process (MDP). While an MDP describes the environment and the decision-making framework, the Bellman Equation helps us understand how to optimally make decisions (i.e., choose actions) by recursively breaking down problems of optimality.

# What is the Bellman Equation?

The Bellman Equation tells us how to compute the value of a state, which is the expected long-term reward starting from that state and following a particular policy (a strategy for choosing actions). It decomposes the value of a state into two parts:

The immediate reward from being in that state.
The expected value of the next state (which depends on the chosen action and the transition probabilities).
Bellman Equation for State-Value (V-function)
For a given policy
𝜋
π, the state-value function
𝑉
𝜋
(
𝑠
)
V
π
 (s) is defined as:


𝑉
𝜋
(
𝑠
)
=
𝐸
[
𝑅
𝑡
+
𝛾
𝑉
𝜋
(
𝑠
𝑡
+
1
)
∣
𝑠
𝑡
=
𝑠
]
V
π
 (s)=E[R
t
​
 +γV
π
 (s
t+1
​
 )∣s
t
​
 =s]

Where:

𝑉
𝜋
(
𝑠
)
V
π
 (s): Value of state
𝑠
s under policy
𝜋
π.

𝑅
𝑡
R
t
​
 : Reward received after taking an action at time step
𝑡
t.

𝛾
γ: Discount factor (0 ≤
𝛾
γ ≤ 1), which determines the importance of future rewards. If
𝛾
γ is close to 1, future rewards are considered more important.

𝑠
𝑡
+
1
s
t+1
​
 : The next state after taking an action.

This equation is recursive, meaning the value of the current state depends on the value of the next state, and so on.




# Difference Between MDP and Bellman Equation MDP:

**MDP:** Describes the environment (states, actions, transitions, rewards) and defines how the agent interacts with the environment.

**Bellman Equation:** Describes how to compute the value of states and actions by recursively breaking down the problem into immediate reward and future reward. It helps in solving the MDP by finding the value of each state and determining the best policy to follow.

In short, the MDP gives you the structure of the problem, while the Bellman Equation provides the mathematical framework to solve that problem by finding optimal strategies (policies) for decision-making.

# Example with Python Code
Let's take a simplified gridworld and apply the Bellman Equation. We'll calculate the value of each state based on random rewards and transitions.

In [1]:
import numpy as np

# Define the grid size and discount factor
grid_size = 4
gamma = 0.9

# Initialize a random reward matrix for each state
reward_matrix = np.random.uniform(-1, 1, (grid_size, grid_size))

# Initialize the value function for each state as zeros
value_function = np.zeros((grid_size, grid_size))

# Bellman equation iteration
def bellman_update(value_function, reward_matrix, gamma, iterations=10):
    for _ in range(iterations):
        new_value_function = np.copy(value_function)
        for i in range(grid_size):
            for j in range(grid_size):
                # For simplicity, assume actions lead to the neighboring states deterministically
                # Calculate value based on neighboring states (up, down, left, right)
                neighbors = []
                if i > 0: neighbors.append(value_function[i-1, j])  # Up
                if i < grid_size-1: neighbors.append(value_function[i+1, j])  # Down
                if j > 0: neighbors.append(value_function[i, j-1])  # Left
                if j < grid_size-1: neighbors.append(value_function[i, j+1])  # Right

                # Bellman update: current reward + discounted value of the best neighboring state
                best_neighbor_value = max(neighbors) if neighbors else 0
                new_value_function[i, j] = reward_matrix[i, j] + gamma * best_neighbor_value

        value_function = new_value_function  # Update value function

    return value_function

# Apply the Bellman equation to update value functions
updated_value_function = bellman_update(value_function, reward_matrix, gamma)
print("Updated Value Function:")
print(updated_value_function)


Updated Value Function:
[[3.83824622 3.94704488 3.51919715 2.86795924]
 [3.58631347 3.85965337 2.53612369 3.41383342]
 [2.81434937 3.80723306 3.70478639 3.20305854]
 [2.59295105 2.55822991 3.18615782 2.9420762 ]]


# Explanation:
Reward Matrix: We randomly initialize a reward matrix where each state has some reward.
Value Function: Initially, we start with a value of zero for all states.
Bellman Update: For each state, we look at the neighboring states (UP, DOWN, LEFT, RIGHT) and calculate the updated value using the Bellman equation. The new value is the immediate reward plus the discounted value of the best neighboring state.
# Bellman Equation in Action:
This code simulates the process of updating the state-value function based on rewards and future expected rewards.
The state values gradually update over iterations to reflect the expected long-term reward from each state.